### ISSUE TITLE
css not load 

### ISSUE THREAD

**Issue by jimit-hothi** [hashimi/dynamic-headers#1]
when i add

add_css(array('style.css'));

in head section but my css not load

can you guide where is my problem .

my css location is -

http://localhost/codeigniter/css/style.css

my problem location  is -

 http://localhost/codeigniter/

thank you

**Comment by jamshidhashimi** [comment]
Did you setup your config.php? see the last lines here: https://github.com/hashimi/dynamic-headers/blob/master/application/config/config.php

Also, check the blog post I wrote, and double check if you are missing any step: http://jamshidhashimi.com/2013/04/12/dynamically-add-javascript-and-css-files-in-codeigniter-header-page/

**Comment by jimit-hothi** [comment]
yes i can add this but still not load

my ci 3.1.3 

maybe version problem ???

**Comment by jimit-hothi** [comment]
put_header call in view then get error see below

> 
A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: helpers/assets_helper.php

Line Number: 71

Backtrace:

File: /opt/lampp/htdocs/base_controller/application/helpers/assets_helper.php
Line: 71
Function: _error_handler

File: /opt/lampp/htdocs/base_controller/application/views/welcome_message.php
Line: 12
Function: put_headers

File: /opt/lampp/htdocs/base_controller/application/controllers/Welcome.php
Line: 24
Function: view

File: /opt/lampp/htdocs/base_controller/index.php
Line: 315
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: helpers/assets_helper.php

Line Number: 75

Backtrace:

File: /opt/lampp/htdocs/base_controller/application/helpers/assets_helper.php
Line: 75
Function: _error_handler

File: /opt/lampp/htdocs/base_controller/application/views/welcome_message.php
Line: 12
Function: put_headers

File: /opt/lampp/htdocs/base_controller/application/controllers/Welcome.php
Line: 24
Function: view

File: /opt/lampp/htdocs/base_controller/index.php
Line: 315
Function: require_once

**Comment by jimit-hothi** [comment]
Thanks issue Solved.
