### ISSUE TITLE
Link in the head not shown

### ISSUE THREAD

**Issue by samuelesantoni** [hashimi/dynamic-headers#2]
I have some problem for implement this function. What i do:
1) inside the folder helpers, i have created a file called function_helper.php whit this code:
```
//Dynamically add Javascript files to header page
if(!function_exists('add_js')){
  function add_js($file='')
  {
    $str = '';
    $ci = &get_instance();
    $header_js  = $ci->config->item('header_js');
    if(empty($file)){
      return;
    }
    if(is_array($file)){
      if(!is_array($file) && count($file) <= 0){
        return;
      }
      foreach($file AS $item){
        $header_js[] = $item;
      }
      $ci->config->set_item('header_js',$header_js);
    }else{
      $str = $file;
      $header_js[] = $str;
      $ci->config->set_item('header_js',$header_js);
    }
  }
}

//Dynamically add CSS files to header page
if(!function_exists('add_css')){
  function add_css($file='')
  {
    $str = '';
    $ci = &get_instance();
    $header_css = $ci->config->item('header_css');
    if(empty($file)){
      return;
    }
    if(is_array($file)){
      if(!is_array($file) && count($file) <= 0){
        return;
      }
      foreach($file AS $item){
        $header_css[] = $item;
      }
      $ci->config->set_item('header_css',$header_css);
    }else{
      $str = $file;
      $header_css[] = $str;
      $ci->config->set_item('header_css',$header_css);
    }
  }
}

//Putting our CSS and JS files together
if(!function_exists('put_headers')){
  function put_headers()
  {
    $str = '';
    $ci = &get_instance();
    $header_css = $ci->config->item('header_css');
    $header_js  = $ci->config->item('header_js');
    foreach($header_css AS $item){
      $str .= '<link rel="stylesheet" href="'.base_url().'css/'.$item.'" type="text/css" />'."\n";
    }
    foreach($header_js AS $item){
      $str .= '<script type="text/javascript" src="'.base_url().'js/'.$item.'"></script>'."\n";
    }
    return $str;
  }
}
```
2)inside the file config.php i have added this:
```
$config['header_css'] = array();
$config['header_js']  = array('jquery.particleground.min.js');
```

3)inside my controller called Home i have added:
```
class Home extends CI_Controller {
	public function index()
	{
		$data['title'] = "my title";
		$data['description'] = 'my description';

		$this->lang->load('it', 'italian');

		$this->load->helper('url');
		$this->load->helper('function');

		add_js('jquery.particleground.min.js');

		$this->load->view('head', $data);
		$this->load->view('navbar');
		$this->load->view('home');
		$this->load->view('footer');
	}
}
```
but inside the "head" there isn't anything!
Codeigniter don't report errors.

Someone can help me please? Thanks.

**Comment by jamshidhashimi** [comment]
Update your function_helper with put_headers() function as I created here: https://github.com/hashimi/dynamic-headers/blob/master/application/helpers/function_helper.php 
and then use that function in your view page (for example your header view or anywhere), as I used here: https://github.com/hashimi/dynamic-headers/blob/master/application/views/welcome_message.php

**Comment by samuelesantoni** [comment]
Thanks for have help me. 
I have only one issue. 
The link is show 2 times but in config, inside the array i have wrote only 1 time. 
How can solve this?
Thanks.

**Comment by jamshidhashimi** [comment]
Can you please post your code here? as I couldn't understand your question.

**Comment by samuelesantoni** [comment]
Hi, sorry for my late answer.
I have 2 question for you:

1) I have 2 link in my footer with the same js.
I put in the footer:
```
<?php echo put_headers(); ?>
```
but the result is in the screenshot. I have a "double link" with my js.

2) The second question is: how can i call a specific js or css?
Is correct this code?
```
<?php echo put_headers(array('first.js', 'second.js' )); ?>
```

Thanks!
![screenshot](https://user-images.githubusercontent.com/19838074/30021254-06194ea6-9167-11e7-84c3-d5a1461010f0.png)

**Comment by jamshidhashimi** [comment]
As you can see the helper file, it looks the config file and print the array variables coming from the config file. 
`$header_css = $ci->config->item('header_css');
  $header_js  = $ci->config->item('header_js');`

So check your config file for `$header_css` and `$header_js` arrays and make sure that you don't have any JS files twice there or not already having it as hard code in your footer.
